# Two libvirt VMs on qemu:///system, both booting UEFI (OVMF, secure boot
# off) with an emulated TPM 2.0 (swtpm), a plain VGA adapter and a VNC
# display on localhost (open them in virt-manager, or point any VNC viewer at
# 127.0.0.1 and the VM's vncPort below):
#
#   harmonia-kali    Kali Linux, installed with the i3 desktop. Has a
#                    read-write virtiofs share with the host (tag "shared",
#                    ~/vms/kali-shared on the host, ~/shared in the guest).
#                    On every boot the harmonia-vms service puts an install
#                    script there (harmonia/install.py) with the i3 config
#                    from vms/kali-i3.nix, the bash setup and this flake's
#                    neovim config.
#
# Both VMs' networking is filtered on the host (vms/firewall.nix): pick a
# policy per VM below, or switch a running one with harmonia-vm-firewall.
#   harmonia-ubuntu  Ubuntu Desktop (GNOME), stock.
#
# The domains and their empty disks are created by the harmonia-vms service
# on boot. The installer ISOs are several GB, so they are not part of the
# build: `sudo harmonia-vm-fetch` downloads the pinned versions and checks them.
#
# harmonia-vms, harmonia-vm-fetch and harmonia-vm-firewall are one Python
# script (vms/harmonia-vms.py), all three on your PATH.
{
  config,
  lib,
  pkgs,
  palette,
  keys,
  username,
  ...
}:
let
  imageDir = "/var/lib/libvirt/images";
  pyScript = import ../../lib/python-script.nix { inherit pkgs lib; };
  hm = config.home-manager.users.${username};

  kaliI3 = import ../../vms/kali-i3.nix { inherit palette keys; };
  firewall = import ../../vms/firewall.nix { inherit lib; };

  # Neovim exactly as home-manager sets it up on the host: init.lua, the
  # other nvim/ config files (colours, lualine theme) and the plugin pack
  # (plugins + treesitter grammars), copied as real files so the guest can
  # read them without /nix/store.
  nvimConfigFiles = lib.filter (
    f: f.enable && lib.hasPrefix "nvim/" f.target && f.target != "nvim/init.lua"
  ) (lib.attrValues hm.xdg.configFile);
  nvimInit = pkgs.writeText "init.lua" hm.programs.neovim.initLua;
  nvimPack = hm.xdg.dataFile."nvim/site/pack/hm".source;

  # bash as on the host: the same history settings, shell options,
  # aliases, prompt, fzf colours and readline (vi mode) config, pointed at
  # Debian's paths instead of /nix/store. Host-only aliases are dropped.
  hmBash = hm.programs.bash;
  kaliAliases =
    lib.removeAttrs hmBash.shellAliases [
      "zen"
      "rebuild"
    ]
    // {
      fd = "fdfind"; # Debian's name for fd
    };
  onOff = v: if lib.isBool v then (if v then "on" else "off") else toString v;
  kaliInputrc = pkgs.writeText "inputrc" ''
    $include /etc/inputrc
    ${lib.concatStrings (
      lib.mapAttrsToList (k: v: "set ${k} ${onOff v}\n") hm.programs.readline.variables
    )}
    ${hm.programs.readline.extraConfig}
  '';
  kaliBashrc = pkgs.writeText "bashrc" ''
    # harmonia's bash config (generated by modules/nixos/vms.nix).
    [[ $- == *i* ]] || return

    HISTCONTROL=${lib.concatStringsSep ":" hmBash.historyControl}
    HISTSIZE=${toString hmBash.historySize}
    HISTFILESIZE=${toString hmBash.historyFileSize}
    shopt -s ${toString hmBash.shellOptions}

    ${lib.concatStrings (
      lib.mapAttrsToList (
        k: v: "export ${k}=${lib.escapeShellArg (toString v)}\n"
      ) hmBash.sessionVariables
    )}
    ${lib.concatStrings (lib.mapAttrsToList (k: v: "alias ${k}=${lib.escapeShellArg v}\n") kaliAliases)}
    [ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion
    eval "$(dircolors -b)"

    export FZF_DEFAULT_OPTS=${
      lib.escapeShellArg (
        "--color "
        + lib.concatStringsSep "," (lib.mapAttrsToList (k: v: "${k}:${v}") hm.programs.fzf.colors)
      )
    }
    eval "$(fzf --bash)"

    ${import ../../home/bash-prompt.nix {
      inherit palette;
      gitPrompt = "/usr/lib/git-core/git-sh-prompt";
      gpg = hm.programs.gpg.package;
    }}
  '';

  # Run inside Kali: installs i3 and the tools the config uses, then copies
  # everything into place (existing files are kept as *.bak).
  kaliInstall = pkgs.writeScript "install.py" (
    builtins.replaceStrings
      [ ''HOST_SHARE = "the host's share"'' ]
      [ ''HOST_SHARE = "${kaliRwShare}"'' ]
      (builtins.readFile ../../vms/kali-install.py)
  );

  # Everything install.py copies, put into the read-write share on boot.
  kaliBundle = pkgs.runCommand "harmonia-kali-bundle" { } ''
    mkdir -p $out/i3 $out/i3status $out/nvim/config $out/bash
    cp ${pkgs.writeText "harmonia-status" kaliI3.status} $out/harmonia-status
    cp ${kaliBashrc} $out/bash/bashrc
    cp ${kaliInputrc} $out/bash/inputrc
    cp ${pkgs.writeText "i3-config" kaliI3.i3} $out/i3/config
    cp ${pkgs.writeText "i3status-config" kaliI3.i3status} $out/i3status/config
    cp ${../../assets/wallpaper.png} $out/wallpaper.png
    cp ${kaliInstall} $out/install.py

    cp ${nvimInit} $out/nvim/config/init.lua
    ${lib.concatMapStrings (f: ''
      mkdir -p "$(dirname "$out/nvim/config/${lib.removePrefix "nvim/" f.target}")"
      cp -rL ${f.source} "$out/nvim/config/${lib.removePrefix "nvim/" f.target}"
    '') nvimConfigFiles}
    cp -rL ${nvimPack} $out/nvim/pack
  '';

  # Read-write share with the Kali guest (mount tag "shared", ~/shared in
  # the guest). Your user owns it; the guest's first user has the same uid.
  kaliRwShare = "/home/${username}/vms/kali-shared";

  # Installer images, pinned by release. `sha256 = null` means the checksum is
  # read from the release's own SHA256SUMS at download time (and printed, so
  # it can be pinned here).
  vms = {
    kali = {
      memory = 4096;
      vcpus = 4;
      vncPort = 5900;
      disk = "60G";
      iso = {
        name = "kali-linux-2026.2-installer-amd64.iso";
        url = "https://cdimage.kali.org/kali-2026.2/kali-linux-2026.2-installer-amd64.iso";
        sums = "https://cdimage.kali.org/kali-2026.2/SHA256SUMS";
        sha256 = null;
      };
      share = kaliRwShare;
      bundle = kaliBundle;
      # Host-enforced network policy (vms/firewall.nix): open, internet-only
      # or isolated, plus optional raw nwfilter <rule>s in extraRules.
      # Switch a running VM with `harmonia-vm-firewall kali isolated`.
      firewall.policy = "open";
    };
    ubuntu = {
      memory = 6144;
      vcpus = 4;
      vncPort = 5901;
      disk = "60G";
      iso = {
        name = "ubuntu-26.04.1-desktop-amd64.iso";
        url = "https://releases.ubuntu.com/26.04.1/ubuntu-26.04.1-desktop-amd64.iso";
        sums = "https://releases.ubuntu.com/26.04.1/SHA256SUMS";
        sha256 = "601e30fbf5d97759367c632e2c33630665039b7e2158fd068403da3ccf1bda1f";
      };
      share = null;
      bundle = null;
      firewall.policy = "open";
    };
  };

  domainXml =
    name: vm:
    pkgs.writeText "harmonia-${name}.xml" ''
      <domain type="kvm">
        <name>harmonia-${name}</name>
        <memory unit="MiB">${toString vm.memory}</memory>
        <vcpu>${toString vm.vcpus}</vcpu>
        <os firmware="efi">
          <type arch="x86_64" machine="q35">hvm</type>
          <firmware><feature enabled="no" name="secure-boot"/></firmware>
          <boot dev="hd"/>
          <boot dev="cdrom"/>
        </os>
        <features><acpi/><apic/></features>
        <cpu mode="host-passthrough"/>
        <clock offset="utc"/>
        ${lib.optionalString (vm.share != null) ''
          <memoryBacking><source type="memfd"/><access mode="shared"/></memoryBacking>
        ''}
        <devices>
          <disk type="file" device="disk">
            <driver name="qemu" type="qcow2" discard="unmap"/>
            <source file="${imageDir}/harmonia-${name}.qcow2"/>
            <target dev="vda" bus="virtio"/>
          </disk>
          <disk type="file" device="cdrom">
            <driver name="qemu" type="raw"/>
            <source file="${imageDir}/${vm.iso.name}"/>
            <target dev="sda" bus="sata"/>
            <readonly/>
          </disk>
          <interface type="network">
            <source network="default"/>
            <model type="virtio"/>
            <filterref filter="harmonia-vm-${name}"/>
          </interface>
          <graphics type="vnc" port="${toString vm.vncPort}" autoport="no">
            <listen type="address" address="127.0.0.1"/>
          </graphics>
          <video>
            <model type="vga" vram="16384" heads="1" primary="yes"/>
          </video>
          <channel type="unix">
            <target type="virtio" name="org.qemu.guest_agent.0"/>
          </channel>
          <input type="tablet" bus="usb"/>
          <tpm model="tpm-crb">
            <backend type="emulator" version="2.0"/>
          </tpm>
          <rng model="virtio">
            <backend model="random">/dev/urandom</backend>
          </rng>
          ${lib.optionalString (vm.share != null) ''
            <filesystem type="mount" accessmode="passthrough">
              <driver type="virtiofs"/>
              <source dir="${vm.share}"/>
              <target dir="shared"/>
            </filesystem>
          ''}
        </devices>
      </domain>
    '';

  # nwfilter XML: the shared policies, and every VM filter for every policy
  # (so harmonia-vm-firewall can switch without a rebuild).
  policyXml = lib.mapAttrs (p: xml: pkgs.writeText "harmonia-${p}.xml" xml) firewall.policyFilters;
  vmFilterXml =
    name: vm: policy:
    pkgs.writeText "harmonia-vm-${name}-${policy}.xml" (
      firewall.vmFilter name (vm.firewall // { inherit policy; })
    );

  # What vms/harmonia-vms.py needs to know about this build.
  vmsConfig = pkgs.writeText "harmonia-vms.json" (
    builtins.toJSON {
      inherit imageDir username;
      policies = map (p: {
        name = p;
        xml = policyXml.${p};
      }) firewall.policies;
      vms = lib.mapAttrs (name: vm: {
        inherit (vm) iso disk share;
        bundle = if vm.bundle == null then null else "${vm.bundle}";
        domain = domainXml name vm;
        policy = vm.firewall.policy;
        filters = lib.genAttrs firewall.policies (vmFilterXml name vm);
      }) vms;
    }
  );

  # harmonia-vms (run by the service below), harmonia-vm-fetch and
  # harmonia-vm-firewall: the same script, told which one it is.
  vmsCommand =
    name:
    pyScript name {
      runtimeInputs = [
        config.virtualisation.libvirtd.package
        pkgs.qemu_kvm
      ];
      replace = {
        "COMMAND = \"harmonia-vms\"" = ''COMMAND = "${name}"'';
        "CONFIG_FILE = \"harmonia-vms.json\"" = ''CONFIG_FILE = "${vmsConfig}"'';
      };
    } ../../vms/harmonia-vms.py;
  defineVms = vmsCommand "harmonia-vms";
  fetch = vmsCommand "harmonia-vm-fetch";
  vmFirewall = vmsCommand "harmonia-vm-firewall";
in
{
  environment.systemPackages = [
    defineVms
    fetch
    vmFirewall
  ];

  systemd.tmpfiles.rules = [
    "d /home/${username}/vms 0755 ${username} users -"
    "d ${kaliRwShare} 0755 ${username} users -"
  ];

  # (Re)define the domains and create any missing disks. Re-running `virsh
  # define` updates a domain in place; a running VM picks it up on next boot.
  systemd.services.harmonia-vms = {
    description = "Define the harmonia libvirt VMs";
    after = [ "libvirtd.service" ];
    requires = [ "libvirtd.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${defineVms}/bin/harmonia-vms";
    };
  };
}
