# Two libvirt VMs on qemu:///system, both with a plain VGA adapter and a VNC
# display on localhost (open them in virt-manager, or point any VNC viewer at
# 127.0.0.1 and the VM's vncPort below):
#
#   harmonia-kali    Kali Linux, installed with the i3 desktop. Has a
#                    read-write virtiofs share with the host (tag "shared",
#                    ~/vms/kali-shared on the host, ~/shared in the guest).
#                    On every boot the harmonia-vms service puts an install
#                    script there (harmonia/install.sh) with the i3 config
#                    from vms/kali-i3.nix, the bash setup and this flake's
#                    neovim config.
#
# Both VMs' networking is filtered on the host (vms/firewall.nix): pick a
# policy per VM below, or switch a running one with harmonia-vm-firewall.
#   harmonia-ubuntu  Ubuntu Desktop (GNOME), stock.
#
# The domains and their empty disks are created by the harmonia-vms service
# on boot. The installer ISOs are several GB, so they are not part of the
# build: `sudo harmonia-vm-fetch` downloads the pinned versions and checks them.
{
  config,
  lib,
  pkgs,
  palette,
  keys,
  username,
  ...
}:
let
  imageDir = "/var/lib/libvirt/images";
  hm = config.home-manager.users.${username};

  kaliI3 = import ../../vms/kali-i3.nix { inherit palette keys; };
  firewall = import ../../vms/firewall.nix { inherit lib; };

  # Neovim exactly as home-manager sets it up on the host: init.lua, the
  # other nvim/ config files (colours, lualine theme) and the plugin pack
  # (plugins + treesitter grammars), copied as real files so the guest can
  # read them without /nix/store.
  nvimConfigFiles = lib.filter (f: f.enable && lib.hasPrefix "nvim/" f.target && f.target != "nvim/init.lua") (
    lib.attrValues hm.xdg.configFile
  );
  nvimInit = pkgs.writeText "init.lua" hm.programs.neovim.initLua;
  nvimPack = hm.xdg.dataFile."nvim/site/pack/hm".source;

  # bash as on the host: the same history settings, shell options,
  # aliases, prompt, fzf colours and readline (vi mode) config, pointed at
  # Debian's paths instead of /nix/store. Host-only aliases are dropped.
  hmBash = hm.programs.bash;
  kaliAliases =
    lib.removeAttrs hmBash.shellAliases [
      "zen"
      "rebuild"
    ]
    // {
      fd = "fdfind"; # Debian's name for fd
    };
  onOff = v: if lib.isBool v then (if v then "on" else "off") else toString v;
  kaliInputrc = pkgs.writeText "inputrc" ''
    $include /etc/inputrc
    ${lib.concatStrings (
      lib.mapAttrsToList (k: v: "set ${k} ${onOff v}\n") hm.programs.readline.variables
    )}
    ${hm.programs.readline.extraConfig}
  '';
  kaliBashrc = pkgs.writeText "bashrc" ''
    # harmonia's bash config (generated by modules/nixos/vms.nix).
    [[ $- == *i* ]] || return

    HISTCONTROL=${lib.concatStringsSep ":" hmBash.historyControl}
    HISTSIZE=${toString hmBash.historySize}
    HISTFILESIZE=${toString hmBash.historyFileSize}
    shopt -s ${toString hmBash.shellOptions}

    ${lib.concatStrings (
      lib.mapAttrsToList (k: v: "export ${k}=${lib.escapeShellArg (toString v)}\n") hmBash.sessionVariables
    )}
    ${lib.concatStrings (
      lib.mapAttrsToList (k: v: "alias ${k}=${lib.escapeShellArg v}\n") kaliAliases
    )}
    [ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion
    eval "$(dircolors -b)"

    export FZF_DEFAULT_OPTS=${
      lib.escapeShellArg (
        "--color "
        + lib.concatStringsSep "," (lib.mapAttrsToList (k: v: "${k}:${v}") hm.programs.fzf.colors)
      )
    }
    eval "$(fzf --bash)"

    ${import ../../home/bash-prompt.nix {
      inherit palette;
      gitPrompt = "/usr/lib/git-core/git-sh-prompt";
    }}
  '';

  # Run inside Kali: installs i3 and the tools the config uses, then copies
  # everything into place (existing files are kept as *.bak).
  kaliInstall = pkgs.writeText "install.sh" ''
    #!/bin/sh
    # Usage (in the Kali guest; see docs/vms-and-containers.md):
    #   mkdir -p ~/shared && sudo mount -t virtiofs shared ~/shared
    #   sh ~/shared/harmonia/install.sh
    set -eu
    src=$(dirname "$(readlink -f "$0")")

    sudo apt-get update
    sudo apt-get install -y kali-desktop-i3 i3status rofi dunst feh maim xclip \
      i3lock xss-lock x11-xserver-utils python3 alacritty neovim ripgrep \
      fd-find git bash-completion fzf tmux ranger

    put() { # put <source> <dest>
      mkdir -p "$(dirname "$2")"
      [ -e "$2" ] && rm -rf "$2.bak" && mv "$2" "$2.bak"
      cp -rL "$1" "$2"
      chmod -R u+w "$2"
    }
    put "$src/i3/config"        "$HOME/.config/i3/config"
    put "$src/i3status/config"  "$HOME/.config/i3status/config"
    put "$src/harmonia-status"  "$HOME/.local/bin/harmonia-status"
    chmod +x "$HOME/.local/bin/harmonia-status"
    put "$src/wallpaper.png"    "$HOME/.local/share/harmonia/wallpaper.png"
    put "$src/nvim/config"      "$HOME/.config/nvim"
    put "$src/nvim/pack"        "$HOME/.local/share/nvim/site/pack/hm"
    put "$src/bash/bashrc"      "$HOME/.bashrc"
    put "$src/bash/inputrc"     "$HOME/.inputrc"

    # bash instead of Kali's default zsh
    [ "$(getent passwd "$USER" | cut -d: -f7)" = /bin/bash ] || sudo chsh -s /bin/bash "$USER"

    # Mount the read-write share (host: ${kaliRwShare}) at ~/shared on boot.
    mkdir -p "$HOME/shared"
    grep -q '^shared ' /etc/fstab ||
      echo "shared $HOME/shared virtiofs defaults,nofail 0 0" | sudo tee -a /etc/fstab >/dev/null
    sudo systemctl daemon-reload

    echo "Done. Log out and pick i3 at the login screen; the i3 modifier is Alt."
    echo "~/shared is the read-write share with the host; re-run this script after a host rebuild to update."
  '';

  # Everything install.sh copies, put into the read-write share on boot.
  kaliBundle = pkgs.runCommand "harmonia-kali-bundle" { } ''
    mkdir -p $out/i3 $out/i3status $out/nvim/config $out/bash
    cp ${pkgs.writeText "harmonia-status" kaliI3.status} $out/harmonia-status
    cp ${kaliBashrc} $out/bash/bashrc
    cp ${kaliInputrc} $out/bash/inputrc
    cp ${pkgs.writeText "i3-config" kaliI3.i3} $out/i3/config
    cp ${pkgs.writeText "i3status-config" kaliI3.i3status} $out/i3status/config
    cp ${../../assets/wallpaper.png} $out/wallpaper.png
    cp ${kaliInstall} $out/install.sh

    cp ${nvimInit} $out/nvim/config/init.lua
    ${lib.concatMapStrings (f: ''
      mkdir -p "$(dirname "$out/nvim/config/${lib.removePrefix "nvim/" f.target}")"
      cp -rL ${f.source} "$out/nvim/config/${lib.removePrefix "nvim/" f.target}"
    '') nvimConfigFiles}
    cp -rL ${nvimPack} $out/nvim/pack
  '';

  # Read-write share with the Kali guest (mount tag "shared", ~/shared in
  # the guest). Your user owns it; the guest's first user has the same uid.
  kaliRwShare = "/home/${username}/vms/kali-shared";

  # Installer images, pinned by release. `sha256 = null` means the checksum is
  # read from the release's own SHA256SUMS at download time (and printed, so
  # it can be pinned here).
  vms = {
    kali = {
      memory = 4096;
      vcpus = 4;
      vncPort = 5900;
      disk = "60G";
      iso = {
        name = "kali-linux-2026.2-installer-amd64.iso";
        url = "https://cdimage.kali.org/kali-2026.2/kali-linux-2026.2-installer-amd64.iso";
        sums = "https://cdimage.kali.org/kali-2026.2/SHA256SUMS";
        sha256 = null;
      };
      share = kaliRwShare;
      bundle = kaliBundle;
      # Host-enforced network policy (vms/firewall.nix): open, internet-only
      # or isolated, plus optional raw nwfilter <rule>s in extraRules.
      # Switch a running VM with `harmonia-vm-firewall kali isolated`.
      firewall.policy = "open";
    };
    ubuntu = {
      memory = 6144;
      vcpus = 4;
      vncPort = 5901;
      disk = "60G";
      iso = {
        name = "ubuntu-26.04.1-desktop-amd64.iso";
        url = "https://releases.ubuntu.com/26.04.1/ubuntu-26.04.1-desktop-amd64.iso";
        sums = "https://releases.ubuntu.com/26.04.1/SHA256SUMS";
        sha256 = "601e30fbf5d97759367c632e2c33630665039b7e2158fd068403da3ccf1bda1f";
      };
      share = null;
      bundle = null;
      firewall.policy = "open";
    };
  };

  domainXml =
    name: vm:
    pkgs.writeText "harmonia-${name}.xml" ''
      <domain type="kvm">
        <name>harmonia-${name}</name>
        <memory unit="MiB">${toString vm.memory}</memory>
        <vcpu>${toString vm.vcpus}</vcpu>
        <os firmware="efi">
          <type arch="x86_64" machine="q35">hvm</type>
          <firmware><feature enabled="no" name="secure-boot"/></firmware>
          <boot dev="hd"/>
          <boot dev="cdrom"/>
        </os>
        <features><acpi/><apic/></features>
        <cpu mode="host-passthrough"/>
        <clock offset="utc"/>
        ${lib.optionalString (vm.share != null) ''
          <memoryBacking><source type="memfd"/><access mode="shared"/></memoryBacking>
        ''}
        <devices>
          <disk type="file" device="disk">
            <driver name="qemu" type="qcow2" discard="unmap"/>
            <source file="${imageDir}/harmonia-${name}.qcow2"/>
            <target dev="vda" bus="virtio"/>
          </disk>
          <disk type="file" device="cdrom">
            <driver name="qemu" type="raw"/>
            <source file="${imageDir}/${vm.iso.name}"/>
            <target dev="sda" bus="sata"/>
            <readonly/>
          </disk>
          <interface type="network">
            <source network="default"/>
            <model type="virtio"/>
            <filterref filter="harmonia-vm-${name}"/>
          </interface>
          <graphics type="vnc" port="${toString vm.vncPort}" autoport="no">
            <listen type="address" address="127.0.0.1"/>
          </graphics>
          <video>
            <model type="vga" vram="16384" heads="1" primary="yes"/>
          </video>
          <channel type="unix">
            <target type="virtio" name="org.qemu.guest_agent.0"/>
          </channel>
          <input type="tablet" bus="usb"/>
          <rng model="virtio">
            <backend model="random">/dev/urandom</backend>
          </rng>
          ${lib.optionalString (vm.share != null) ''
            <filesystem type="mount" accessmode="passthrough">
              <driver type="virtiofs"/>
              <source dir="${vm.share}"/>
              <target dir="shared"/>
            </filesystem>
          ''}
        </devices>
      </domain>
    '';

  # nwfilter XML: the shared policies, and every VM filter for every policy
  # (so harmonia-vm-firewall can switch without a rebuild).
  policyXml = lib.mapAttrs (p: xml: pkgs.writeText "harmonia-${p}.xml" xml) firewall.policyFilters;
  vmFilterXml =
    name: vm: policy:
    pkgs.writeText "harmonia-vm-${name}-${policy}.xml" (firewall.vmFilter name (vm.firewall // { inherit policy; }));

  defineFilters = ''
    ${lib.concatMapStrings (p: "virsh nwfilter-define ${policyXml.${p}}\n") firewall.policies}
  '';

  vmFirewall = pkgs.writeShellApplication {
    name = "harmonia-vm-firewall";
    runtimeInputs = [
      config.virtualisation.libvirtd.package
      pkgs.gnugrep
      pkgs.gnused
    ];
    text = ''
      # Usage: harmonia-vm-firewall                 show each VM's policy
      #        harmonia-vm-firewall VM POLICY       switch it now (${toString firewall.policies})
      # Takes effect on a running VM at once. The policy in modules/nixos/vms.nix
      # comes back on the next boot or rebuild.
      export LIBVIRT_DEFAULT_URI=qemu:///system
      show() {
        for vm in ${toString (lib.attrNames vms)}; do
          policy=$(virsh nwfilter-dumpxml "harmonia-vm-$vm" 2>/dev/null |
            grep -o 'filter="harmonia-[a-z-]*"' | sed 's/filter="harmonia-//; s/"//') || true
          echo "$vm: ''${policy:-not defined}"
        done
      }
      if [ $# -eq 0 ]; then show; exit 0; fi
      [ $# -eq 2 ] || { echo "usage: harmonia-vm-firewall [VM POLICY]" >&2; exit 1; }
      case "$1/$2" in
        ${lib.concatStrings (
          lib.concatLists (
            lib.mapAttrsToList (
              name: vm:
              map (policy: ''
                ${name}/${policy}) virsh nwfilter-define ${vmFilterXml name vm policy} >/dev/null ;;
              '') firewall.policies
            ) vms
          )
        )}
        *) echo "unknown VM or policy (VMs: ${toString (lib.attrNames vms)}; policies: ${toString firewall.policies})" >&2; exit 1 ;;
      esac
      show
    '';
  };

  fetch = pkgs.writeShellApplication {
    name = "harmonia-vm-fetch";
    runtimeInputs = with pkgs; [
      curl
      coreutils
      gawk
    ];
    text = ''
      # Usage: sudo harmonia-vm-fetch [kali|ubuntu]   (default: both)
      fetch() { # fetch <name> <url> <sums-url> <sha256 or "">
        dest=${imageDir}/$1
        if [ -e "$dest" ]; then echo "$1: already downloaded"; return; fi
        expected=$4
        if [ -z "$expected" ]; then
          expected=$(curl -fsSL "$3" | awk -v n="$1" '$2 == n || $2 == "*" n { print $1 }')
          echo "$1: no pinned checksum, using $3: $expected"
        fi
        curl -fL --output "$dest.part" "$2"
        echo "$expected  $dest.part" | sha256sum -c -
        mv "$dest.part" "$dest"
      }
      [ $# -gt 0 ] || set -- ${toString (lib.attrNames vms)}
      for vm in "$@"; do
        case $vm in
          ${lib.concatStrings (
            lib.mapAttrsToList (name: vm: ''
              ${name}) fetch ${vm.iso.name} ${vm.iso.url} ${vm.iso.sums} "${toString vm.iso.sha256}" ;;
            '') vms
          )}
          *) echo "unknown VM: $vm (expected: ${toString (lib.attrNames vms)})" >&2; exit 1 ;;
        esac
      done
    '';
  };
in
{
  environment.systemPackages = [
    fetch
    vmFirewall
  ];

  systemd.tmpfiles.rules = [
    "d /home/${username}/vms 0755 ${username} users -"
    "d ${kaliRwShare} 0755 ${username} users -"
  ];

  # (Re)define the domains and create any missing disks. Re-running `virsh
  # define` updates a domain in place; a running VM picks it up on next boot.
  systemd.services.harmonia-vms = {
    description = "Define the harmonia libvirt VMs";
    after = [ "libvirtd.service" ];
    requires = [ "libvirtd.service" ];
    wantedBy = [ "multi-user.target" ];
    path = [
      config.virtualisation.libvirtd.package
      pkgs.qemu_kvm
    ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      mkdir -p ${imageDir}
      if virsh net-info default >/dev/null 2>&1; then
        virsh net-autostart default
        virsh net-start default 2>/dev/null || true
      fi
      ${defineFilters}
      ${lib.concatStrings (
        lib.mapAttrsToList (name: vm: ''
          virsh nwfilter-define ${vmFilterXml name vm vm.firewall.policy}
          [ -e ${imageDir}/harmonia-${name}.qcow2 ] ||
            qemu-img create -f qcow2 ${imageDir}/harmonia-${name}.qcow2 ${vm.disk}
          virsh define ${domainXml name vm}
          ${lib.optionalString (vm.bundle != null) ''
            mkdir -p ${vm.share}
            rm -rf ${vm.share}/harmonia
            cp -rL ${vm.bundle} ${vm.share}/harmonia
            chmod -R u+w ${vm.share}/harmonia
            chown -R ${username}:users ${vm.share}/harmonia
          ''}
        '') vms
      )}
    '';
  };
}
